### ISSUE TITLE
Module 'asyncio' has no 'create_task' member in Python 3.6

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-dialogue-hermes#2]
rhasspy-dialogue-hermes [fails on Python 3.6](https://github.com/rhasspy/rhasspy-dialogue-hermes/runs/587061573?check_suite_focus=true)

```
 ************* Module rhasspydialogue_hermes
rhasspydialogue_hermes/__init__.py:286:12: E1101: Module 'asyncio' has no 'create_task' member (no-member)
rhasspydialogue_hermes/__init__.py:344:12: E1101: Module 'asyncio' has no 'create_task' member (no-member)
************* Module rhasspydialogue_hermes.__main__
rhasspydialogue_hermes/__main__.py:60:8: E1101: Module 'asyncio' has no 'run' member (no-member)
```

Apparently the `create_task` top-level function was added in Python 3.7, as well as the `run` function:

- https://stackoverflow.com/questions/52796630/python3-6-attributeerror-module-asyncio-has-no-attribute-run
- https://stackoverflow.com/questions/53247533/attributeerror-module-asyncio-has-no-attribute-create-task

Both functions can be replaced to be compatible with Python 3.6, but they make the code uglier. Another option is to require Python 3.7.

How should we handle this? To give an idea about Python versions:

- Ubuntu 18.04 has Python 3.6
- Ubuntu 19.10 has Python 3.7
- Ubuntu 20.04 has Python 3.8
- Raspbian Buster has Python 3.7

**Comment by Xalip** [comment]
Wouldn't it make sense to check the OS on startup and require the correct python version? So basically to maintain the ugly code for some time until the 18.04 LTS version isn't supported anymore? 
Otherwise people who are running 18.04 or Buster are excluded pretty soon.

**Comment by synesthesiam** [comment]
I've switched the minimum Python version for Rhasspy to 3.7 largely because many of the libraries I depend on have long since stopped supporting 3.6.

Luckily, this is a non-issue for anyone using the Docker image. I'm porting the virtualenv install process to GNU autoconf, and there I'm checking for Python 3.7. Given how easy it is to build 3.7 from source and do an "alt install" (so it doesn't mess with your system Python), I don't feel the need to put resources towards 3.6 support.

**Comment by synesthesiam** [comment]
Closing this, since Python seems to be releasing a new version every few months now!
